version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/develop/Dockerfile
    container_name: nextjs
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - my-ecommerce-frontend
      - my-ecomerce-backen

networks:
  my-ecommerce-frontend:
    name: my-ecommerce-frontend
    driver: bridge
  my-ecomerce-backen:
    external: true